### ISSUE TITLE
plot the graph corresponding to baseline.

### ISSUE THREAD

**Issue by amarts** [sac-urs/glusterfs-perf#7]
the baselines should be committed to the repository itself, where as the current result should be updated from local run, and a graph image should be emailed.

**Comment by amarts** [comment]
@aravindavk

**Comment by poornimag** [comment]
We can use Vega for plotting graph (https://vega.github.io/vega/) ?
This works for Jason and yaml format, we can put the test results of releases in new repo or merge it into existing gluster repo. The results I think can be rendered by readthedocs(need to verify), this way we can seemlesly integrate test results to documentation.

**Comment by aravindavk** [comment]
> We can use Vega for plotting graph (https://vega.github.io/vega/) ?
This works for Jason and yaml format, we can put the test results of releases in new repo or merge it into existing gluster repo. The results I think can be rendered by readthedocs(need to verify), this way we can seemlesly integrate test results to documentation.

Nice. But Javascript libraries are mostly suitable for plotting graphs on the web. (Server side install dependencies are more. Not sure easily possible or not).

Python matplotlib(https://matplotlib.org/) can be used to plot graph after Perf run and send email as an attachment with the result.

**Comment by amarts** [comment]
This now works with #11

**Comment by amarts** [comment]
@poornimag the output looks like #15 now.. hopefully that is enough.
