### ISSUE TITLE
how did we decide which hosts are clients?

### ISSUE THREAD

**Issue by amarts** [sac-urs/glusterfs-perf#9]
This is just a question:

We may end up with less or more 'inventory' over time, so, how are we deciding how many clients are there and how many servers are there?

Isn't it better to  define some tests, and clearly identify minimum inventory required for the test? If not satisfied, the test shouldn't even run.

**Comment by sac-urs** [comment]
We expect the user to provide the client details in the variable: glusterfs_perf_client else first server is taken as client. We can have options for multiple clients.

> This is just a question:
> 
> We may end up with less or more 'inventory' over time, so, how are we deciding how many clients are there and how many servers are there?
> 
> Isn't it better to define some tests, and clearly identify minimum inventory required for the test? If not satisfied, the test shouldn't even run.

We can do that.

**Comment by sac-urs** [comment]
This is done, we now have clear separation of servers and clients. And has to be mentioned in the inventory.
